stages:
  - test

run_tests:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apk update
    - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - make test
