version: '3.4'

services:
 
  postgres:
    #container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn coreapp.wsgi -b 0.0.0.0:8000"
    #container_name: app
    depends_on:
      - postgres
    expose:
      - "8000"
    hostname: app
    image: blog-app-image
    networks:
      - main
    restart: on-failure

volumes:
  postgresql-data:
  pgadmin:

networks:
  main:
