version: '3.4'

services:

  app:
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8008:8000"
 
    volumes:
      - .:/app  # just in dev
    depends_on:
      #- monitoring
      - postgres
     # - rabbitmq

  monitoring:
    image: 3megawatt/dev-recruiting-challenge-monitor
    ports:
      - 5000:5000
    # networks:
    #   - main
    hostname: monitoring_service

  pgadmin:
    #container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fm.maghraoui@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # networks:
    #   - main
    restart: unless-stopped
