version: '3.4'

services:

  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn coreapp.wsgi -b 0.0.0.0:8000"
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=coreapp.settings.production
      - SECRET_KEY="yoyo"
    volumes:
      - static:/static
    labels:
    # 
    - "traefik.enable=true"
    - "traefik.docker.network=traefik-proxy"
    - "traefik.http.routers.myblog.rule=Host(`farid-blog.le-5ra.de`, `www.farid-blog.le-5ra.de`) "
    - "traefik.http.routers.myblog.middlewares=secureHeaders@file"
    - "traefik.http.services.myblog.loadbalancer.server.port=8000"
    - "traefik.http.routers.myblog.tls.certresolver=letsencrypt"
    - "traefik.http.routers.myblog.priority=900"
    - "traefik.http.routers.myblog.tls=true"

  # nginx:
  #   #container_name: nginx
  #   command: nginx -g "daemon off;"
  #   depends_on:
  #     - app
  #   image: nginx:alpine
  #   networks:
  #     - main
  #   ports:
  #     - "80:80"
  #   restart: on-failure
  #   volumes:
  #     - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
  #     - static:/var/www/app/static

volumes:
  static:
#networks:
#  main: