version: '3.4'

services:

  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn coreapp.wsgi -b 0.0.0.0:8000"

    environment:
      - DJANGO_SETTINGS_MODULE=coreapp.settings.production
      - SECRET_KEY="yoyo"
    volumes:
      - static:/static

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    depends_on:
      - app
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/app/static

volumes:
  static:
