# Generated by Django 3.2.16 on 2022-10-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(null=True)),
                ('data_hour', models.CharField(max_length=10, null=True)),
                ('energy_expected', models.FloatField(null=True)),
                ('energy_observed', models.FloatField(null=True)),
                ('irradiation_expected', models.FloatField(null=True)),
                ('irradiation_observed', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_data', to='apiapp.plant')),
            ],
        ),
    ]
