# Generated by Django 3.2.16 on 2022-10-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_datapoint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('plant', 'data_date', 'data_hour')},
        ),
    ]
