# Generated by Django 3.2.16 on 2022-10-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_alter_datapoint_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='energy_expected',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='energy_observed',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='irradiation_expected',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='irradiation_observed',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(max_length=10)),
                ('energy_expected', models.FloatField(default=0)),
                ('energy_observed', models.FloatField(default=0)),
                ('irradiation_expected', models.FloatField(default=0)),
                ('irradiation_observed', models.FloatField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_yearly_reports', to='apiapp.plant')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.CharField(max_length=10)),
                ('data_month', models.CharField(max_length=10)),
                ('energy_expected', models.FloatField(default=0)),
                ('energy_observed', models.FloatField(default=0)),
                ('irradiation_expected', models.FloatField(default=0)),
                ('irradiation_observed', models.FloatField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_monthly_reports', to='apiapp.plant')),
            ],
        ),
    ]
